name: GitHub Classroom Workflow
on:
  push:
    branches:
      - master
      - dev
  pull_request:
    branches:
      - master
jobs:
  build:
    name: Autograding
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - uses: docker/setup-buildx-action@v2

      # TODO here tests
      - name: Run rating service unit tests
        run: |
          cd ./src/rsoi_rating
          python3 -m venv venv
          source venv/bin/activate
          pip install -r requirements.txt
          sh run_unit_tests.sh

      - name: Run gateway service unit tests
        run: |
          cd ./src/rsoi_gateway
          python3 -m venv venv
          source venv/bin/activate
          pip install -r requirements.txt
          sh run_unit_tests.sh

      - name: Build images
        timeout-minutes: 10
        run: docker compose build

      - name: Run containers
        timeout-minutes: 5
        run: |
          docker compose up -d
          ./scripts/wait-script.sh
        env:
          WAIT_PORTS: 8080,8070,8060,8050
          LIBRARY_POSTGRES_USER: "${{ secrets.LIBRARY_POSTGRES_USER }}"
          LIBRARY_POSTGRES_PASSWORD: "${{ secrets.LIBRARY_POSTGRES_PASSWORD }}"
          LIBRARY_POSTGRES_DB: "${{ secrets.LIBRARY_POSTGRES_DB }}"
          RATING_POSTGRES_USER: "${{ secrets.RATING_POSTGRES_USER }}"
          RATING_POSTGRES_PASSWORD: "${{ secrets.RATING_POSTGRES_PASSWORD }}"
          RATING_POSTGRES_DB: "${{ secrets.RATING_POSTGRES_DB }}"
          RESERVATION_POSTGRES_USER: "${{ secrets.RESERVATION_POSTGRES_USER }}"
          RESERVATION_POSTGRES_PASSWORD: "${{ secrets.RESERVATION_POSTGRES_PASSWORD }}"
          RESERVATION_POSTGRES_DB: "${{ secrets.RESERVATION_POSTGRES_DB }}"

      - name: Run API Tests
        timeout-minutes: 5
        run: ./scripts/test-script.sh
        env:
          VARIANT: v4
          SERVICE_NAME: rating
          PORT_NUMBER: 8050

      - uses: education/autograding@v1
        id: autograder
        continue-on-error: true

      - name: Stop containers
        if: always()
        continue-on-error: true
        run: |
          docker compose logs
          docker compose down -v